### ISSUE TITLE
Writing our own license

### ISSUE THREAD

**Issue by kenokenobingo** [squatted-online/squatted-online.github.io#12]
What do you think about writing our own libre software license for `squatted.online`?

**Comment by pi43r** [comment]
Good idea! 
Recently I saw someone posting on twitter a license that tries to prevent software for being used in a way that harms people - Espescially underrepresented groups. (of course I can not find it anymore...)

What would be the goal of a squatted license?

**Comment by az3ta** [comment]
This is very interesting @kenokenobingo, do you have more ideas how that could work? Could it be a sort of manifesto?

**Comment by kenokenobingo** [comment]
Definitely a Manifesto as a License (MaaL).

# References
* [Dada Manifesto by Hugo Ball](https://en.wikisource.org/wiki/Dada_Manifesto_(1916,_Hugo_Ball))
* [Situationist Manifesto](https://391.org/manifestos/1960-situationist-manifesto/)

**Comment by Yyyyaaaannnnoooo** [comment]
Where are we at here?
how do we co-write the MaaL?
