### ISSUE TITLE
provide information for RANKS' website

### ISSUE THREAD

**Issue by az3ta** [squatted-online/squatted-online.github.io#17]

**Comment by ariannasmaron** [comment]
promote the even of social media:
- create a facebook event, 
- instagram page
ask people to share / also friends & SOS & Basel Codes & Others

Other platforms?

**Comment by az3ta** [comment]
i was referring to RANK' (Ausstellungsraum Klingental) website
they will create also a fb event, but we have to coordinate it
i'll take care of this

**Comment by az3ta** [comment]
for the website we need to provide:
- picture that gives an impression of the project, somehow
- title
- dates and times of public access
- description of the project
