### ISSUE TITLE
exhibition set up

### ISSUE THREAD

**Issue by Yyyyaaaannnnoooo** [squatted-online/squatted-online.github.io#20]
abbiamo una prima richiesta per il lavoro di Winnie Yoe

"Hi Yann, 

Thanks! Yes, I'll send you the magnet word pieces and the document, you can mail them back after the exhibition. 

For the setup, I cut and used these flexible magnet sheets, about 50x70inch for each (I stuck them onto black foam core for this exhibit which made it easier for setting up but you can also just the sheet directly) — would it be possible to ask you and the team to handle that part?"

**Comment by Yyyyaaaannnnoooo** [comment]
dice di comprare questi: https://www.amazon.com/gp/product/B07NVPNTFZ/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

**Comment by Yyyyaaaannnnoooo** [comment]
We need to prepare website for exhibition:

1. Set rave cave to random beats / might work well with ambient music from website
2. make QR-Codes with link to artwork descriptions
3. create a page for comments from visitors

**Comment by az3ta** [comment]
4. updated homepage (remove submit artwork, add/remove artist with name of the work + link to description)

**Comment by az3ta** [comment]
@Yyyyaaaannnnoooo can you work on 1 and 3? I can look at 2 and 4

**Comment by pi43r** [comment]
I can do 4 now

**Comment by az3ta** [comment]
> I can do 4 now

sounds good
thanks @pi43r

**Comment by az3ta** [comment]
i split this into single issues
