### ISSUE TITLE
Diego Bernaschina

### ISSUE THREAD

**Issue by Yyyyaaaannnnoooo** [squatted-online/squatted-online.github.io#3]
Infinite humanity's part of the homonymous book on science and technology through the futuristic machine "posthumanism" (or the future of humanity) to improve the physical and cognitive abilities of a human species. Manipulating different designs and programming of HTML5 / CSS3 - Javascript - Photoshop - Dreamweaver with sliding on horizontal screen, and different devices (desktop, tablet and mobile) to create a reflective space of the technological processes of humanity. Impossible to predict a question of technology and experimental science applied to the transformation of the human being. So the dehumanization by the absence of the inclusive society to generate such a painful situation.    

It's a collection of graphic designs and webs that use the manipulation and the interactive tests to understand the behavior of users in the digital environment. In general, more variables are manipulated to determine the experimental method of the computer language, or codification through the systematic process in various causes. Using different artistic software programs, both the web developer and the graphic design for the personal computer in general. This allows us to know human existence through emerging technology. To observe a culture favorable to human improvement through our genetic heritage.

**Comment by dbernaschina** [comment]
Hi,
Just that I have my new account, I am barely knowing about this platform. Here I have a link to my work, but I put a private click on it. (or prefer to edit "public").

Link: https://github.com/dbernaschina/Infinite-humanity

You wrote wrong of my last name. I should write correctly "Bernaschina".

Best

**Comment by pi43r** [comment]
Hey Diego, 
The link you posted (infinite-humanity) does not work.
What exactly are you trying to show us?

Understanding github was hard for me, too. Maybe other people can link to good tutorials?

**Comment by dbernaschina** [comment]
Hi,
You can see in: https://htmlpreview.github.io/?https://github.com/dbernaschina/infinite-humanity.io/blob/master/index.html

**Comment by dbernaschina** [comment]
Hi,
Good news! It is already published.
https://dbernaschina.github.io/infinite-humanity.io

**Comment by az3ta** [comment]
> Understanding github was hard for me, too. Maybe other people can link to good tutorials?

See #14

**Comment by az3ta** [comment]
> Hi,
> Good news! It is already published.
> https://dbernaschina.github.io/infinite-humanity.io

Thanks @dbernaschina for the update!
How do you see your project in the squatted pavilion?

**Comment by dbernaschina** [comment]
Hi,
You're welcome.
I don't understand your question. 
It refers to your project.

**Comment by az3ta** [comment]
Dear @dbernaschina , I'm sorry if my question was not clear enough.
I understand you want to explore "human existence through emerging technology". 
And so I was asking: in regards of the Squatted Embassy, how do you see the questions of posthumanism and transhumanist relating with the experiment of applying the principal of the squat culture to the internet? 

From the call:
> In the context of The Wrong 2019 we invite participating artists to take the possibility of squatting a digital space into consideration. As offline and online words have similar characteristics [...]. Therefore, we open a call for the first Basel’s Offline Embassy, inviting artists, coders, designers, and thinkers to re-imagine the website as a possible space to squat.

**Comment by dbernaschina** [comment]
Dear:

My personal opinion about the artwork. However, it is a prediction of the crisis of humanity towards the future. As well as a human species about the danger of advanced technology. The post-human future would not be prepared. For example, the cochlear implant is harming the community without recognizing with sign language for deaf people, that is, it would be in danger for society towards intangible heritage. What happens in the future in advanced technology to eliminate disability. It will be difficult to predict the evolution of humanity for the lives of deaf people.

D.

**Comment by Yyyyaaaannnnoooo** [comment]
This sounds great!
now how do we integrate such ideas in the squatted.online? Would you create a special room / page dedicated to such topic?
I can imagine a part of the squat dedicated to the topic of post-humanism and disability, because it is often the claim of transhumanist: the idea to gene edit disability out of humanity.

**Comment by dbernaschina** [comment]
Look. There are two options: 1) You can use the projector or flat-screen in the hall, or you can also include the conceptual text (include my last reply of this message). 2) You can scan the QR code of my web.

If you have any doubts and please write.

**Comment by Yyyyaaaannnnoooo** [comment]
Dear Diego
we are not looking for finished artworks, the squatted pavillion is about squatting this website, at the exhibition we will show the website, we won't show personal works of the artist, unless the artists thmselve include the artworks in the squatted.online website. We invited you because we like your ideas, it would be great if you could apply them to the squat.

**Comment by dbernaschina** [comment]
Hi.

I get it. I am trying to reread this call. The truth is very complicated to understand the style of computers or algorithms. Quite complex to make my proposal.

It is worth withdrawing my proposal. However, I don't know algorithms, databases or software engineering.

I only make my art proposal.

I hope you understand my message.

**Comment by Yyyyaaaannnnoooo** [comment]
Dear Diego,
you are able to make websites, as proved in the one you sent us, therefore you are more than qualified to participate in this pavillion. None of us knows databases nor engineering, it is about community. Therefore you could, for example, add a room in the squat that is about posthumanism with your website. If you want I can explain you how to do this but is very simple.

**Comment by dbernaschina** [comment]
Hi,
It's okay. Help me understand and analyze my work. He gives me the example of a similar work by another artist who participates in our pavilion.

**Comment by az3ta** [comment]
Dear Diego,
We decided not to include you artwork in the exhibition because not relevant to the topic.
Best, A
