### ISSUE TITLE
pitscher's journal doesn't work on safari

### ISSUE THREAD

**Issue by az3ta** [squatted-online/squatted-online.github.io#30]
the journal is not working on safari.
it displays only the first 3 pages, the rest is blank.

i've notice it also on the computer of the exhibition,
but @Yyyyaaaannnnoooo could you check if you can also reproduce the issue?

on chrome and firefox works fine

**Comment by Yyyyaaaannnnoooo** [comment]
maybe is an issue with the library

**Comment by pi43r** [comment]
Yeah, it's a library issue. 
Safari does not like stars * 

When I opened it, it didn't load as pages, but all the content was there :)
I'm not going to fix this, fuck safari...
Fine?

<img width="890" alt="Schermata 2020-03-03 alle 18 47 17" src="https://user-images.githubusercontent.com/3011806/75804371-2075a780-5d80-11ea-9a5f-a0e6d35ba234.png">

**Comment by andreazaccuri** [comment]
i see the pages but no content

<img width="1387" alt="Screen Shot 2020-03-04 at 21 08 16" src="https://user-images.githubusercontent.com/24527778/75918587-4cfef180-5e5c-11ea-8d2c-0846500a23e3.png">

anyway yes, let's fix it!

**Comment by az3ta** [comment]
i see the pages but no content

mmmh for me would be nice to fix it..
@Yyyyaaaannnnoooo what do you think?

**Comment by Yyyyaaaannnnoooo** [comment]
@pi43r If you can't solve the issue can you put directly the pdf instead of a broken page, or redirect safari/iOS users to the pdf?

**Comment by Yyyyaaaannnnoooo** [comment]
@pi43r I've reverted to the pdf version for now

**Comment by pi43r** [comment]
ok, I thought it could still be accessed through the big [get pdf] button on the page - It doesn't render at all on safari? (Sorry, I have no access to a mac rn)
