### ISSUE TITLE
K E N O

### ISSUE THREAD

**Issue by Yyyyaaaannnnoooo** [squatted-online/squatted-online.github.io#4]
Originally, websites were all about interconnected texts, hypertexts, which is a very intellectual, scientific and literary approach to exchanging thoughts. The so called Web 2.0 was all about connection and interaction. Nowadays, the web tries do redefine itself somewhere between JS apps, giant companies, and decentralized structures.
    Let's bring the agora back to the web! The website as a place of political discourse, where people can collaborate on creating new political concepts in both a an artistic and a theoretical level. Writing, drawing, commiting, pushing. The internet was often portrayed as a political incubator. Nevertheless, the only ideologies being incubated were libertarianism and the alt-right. Let's bring discourse to a progressive community! The digital squat is a workspace, supporting thinkers and activists. Or to put in a 2010-ish way: Occupy the web!

**Comment by kenokenobingo** [comment]
Cf. #10.
